spring:
  application:
    name: ms-ticket
  server:
    port: 8081
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  ticket:
    exchange: ticket.exchange
    routingkey: ticket.routingkey
  data:
    mongodb:
      uri: mongodb://localhost:27017/db_ticket
  cloud:
    feign:
      client:
        config:
          viaCepClient:
            url: https://viacep.com.br/

